version: '3'

services:
    nginx:
        image: nginx:latest
        volumes:
            - ./build/nginx/:/etc/nginx/conf.d/
            - ./symfony/:/var/www/symfony/
        ports:
            - 80:80
        networks:
            - symfony
        depends_on: 
            - php
    php:
        build:
            context: .
            dockerfile: Dockerfile-php
        environment:
            APP_ENV: dev # TODO: change this in prod
        volumes:
            - ./symfony/:/var/www/symfony/
        networks:
            - symfony

networks:
    symfony: