version: '3'

services:
    nginx:
        build:
            context: . # TODO: make this different?
            dockerfile: Dockerfile-nginx
        volumes:
            - ./symfony/:/var/www/symfony/
        # Map inbound port 8001 to 80 (HTTP)
        ports:
            - 8001:80
        networks:
            - symfony
    php:
        build:
            context: .
            dockerfile: Dockerfile-php
        ports:
            - 8000:8000
        environment:
            APP_ENV: dev # TODO: change this in prod
        volumes:
            - ./symfony/:/var/www/symfony/
        networks:
            - symfony

networks:
    symfony: