apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  ports:
    # Forward external incoming port 80 to interal port 30080
  - name: nginx
    port: 80
    nodePort: 80
    name: http
  selector:
    app: nginx