apiVersion: apps/v1
kind: Deployment
metadata:
  name: devingunay.com
  labels:
    app: devingunay.com
spec:
  selector:
    matchLabels:
      app: devingunay.com
  template:
    metadata:
      labels:
        app: devingunay.com
    spec:
      containers:
      - name: nginx
        image: nginx
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
      - name: php
        image: php
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9000