#index:
#    path: /
#    controller: App\Controller\DefaultController::index
# navBar:
#   path: /navbar
#   controller: App\Controller\NavBarController::navBar

frontPage:
  path: /
  controller: App\Controller\FrontPageController::frontPage

hobbies:
  path: /hobbies
  controller: App\Controller\HobbiesController::hobbies

about:
  path: /about
  controller: App\Controller\AboutController::about

blog:
  path: /blog
  controller: App\Controller\BlogController::blogFront

# TODO: make this wildcarded or something so it can load any post
# blogPost:
#   path: /blog{$asdfklsdfjlk}
#   controller: App\Controller\BlogController::blogPost
